---
abstract: 'get center point from iArea'
author:
  - 'Tokuhiro Matsuno <tokuhirom aaaatttt gmail dotottto commmmm>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Coordinates-Converter-iArea
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  File::ShareDir: 1.02
  Filter::Util::Call: 0
  Geo::Coordinates::Converter: 0.04
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
