--- 
abstract: get center point from iArea
author: 
  - Tokuhiro Matsuno <tokuhirom aaaatttt gmail dotottto commmmm>
build_requires: 
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.680
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Geo-Coordinates-Converter-iArea
no_index: 
  directory: 
    - inc
    - t
requires: 
  CDB_File: 0
  File::ShareDir: 0
  Geo::Coordinates::Converter: 0
  perl: 5.8.0
version: 0.07
